# Generated by Django 4.0.6 on 2022-07-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventory_quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
