# Generated by Django 4.0.6 on 2022-07-18 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_inventory_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image_link',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
